// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: comment/v1/comment.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 排序规则
type GetCommentRequest_SortType int32

const (
	GetCommentRequest_LIKE_COUNT_DESC  GetCommentRequest_SortType = 0 // 按点赞数降序（默认）
	GetCommentRequest_CREATE_TIME_DESC GetCommentRequest_SortType = 1 // 按创建时间降序
)

// Enum value maps for GetCommentRequest_SortType.
var (
	GetCommentRequest_SortType_name = map[int32]string{
		0: "LIKE_COUNT_DESC",
		1: "CREATE_TIME_DESC",
	}
	GetCommentRequest_SortType_value = map[string]int32{
		"LIKE_COUNT_DESC":  0,
		"CREATE_TIME_DESC": 1,
	}
)

func (x GetCommentRequest_SortType) Enum() *GetCommentRequest_SortType {
	p := new(GetCommentRequest_SortType)
	*p = x
	return p
}

func (x GetCommentRequest_SortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetCommentRequest_SortType) Descriptor() protoreflect.EnumDescriptor {
	return file_comment_v1_comment_proto_enumTypes[0].Descriptor()
}

func (GetCommentRequest_SortType) Type() protoreflect.EnumType {
	return &file_comment_v1_comment_proto_enumTypes[0]
}

func (x GetCommentRequest_SortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetCommentRequest_SortType.Descriptor instead.
func (GetCommentRequest_SortType) EnumDescriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{6, 0}
}

// 点赞评论请求
type LikeCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论唯一标识
	CommentId int64 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 校验规则: 评论ID必须大于0，确保指定了要点赞的具体评论
	// 用户唯一标识
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 校验规则: 用户ID字符串长度必须大于等于1，确保指定了点赞用户身份
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentRequest) Reset() {
	*x = LikeCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentRequest) ProtoMessage() {}

func (x *LikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentRequest.ProtoReflect.Descriptor instead.
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{0}
}

func (x *LikeCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *LikeCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 点赞评论响应
type LikeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 点赞结果
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 点赞后的点赞数
	LikeCount     int64 `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"` // 校验规则: 点赞数必须大于等于0，确保数量为非负数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	mi := &file_comment_v1_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{1}
}

func (x *LikeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LikeResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

// 取消点赞评论请求
type UnlikeCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论唯一标识
	CommentId int64 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 校验规则: 评论ID必须大于0，确保指定了要取消点赞的具体评论
	// 用户唯一标识
	UserId        string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 校验规则: 用户ID字符串长度必须大于等于1，确保指定了取消点赞的用户身份
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeCommentRequest) Reset() {
	*x = UnlikeCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeCommentRequest) ProtoMessage() {}

func (x *UnlikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeCommentRequest.ProtoReflect.Descriptor instead.
func (*UnlikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{2}
}

func (x *UnlikeCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *UnlikeCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 取消点赞评论响应
type UnlikeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 取消点赞结果
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 取消点赞后的点赞数
	LikeCount     int64 `protobuf:"varint,2,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"` // 校验规则: 点赞数必须大于等于0，确保数量为非负数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlikeResponse) Reset() {
	*x = UnlikeResponse{}
	mi := &file_comment_v1_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlikeResponse) ProtoMessage() {}

func (x *UnlikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlikeResponse.ProtoReflect.Descriptor instead.
func (*UnlikeResponse) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{3}
}

func (x *UnlikeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnlikeResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type CreateCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 模块标识，用于区分不同业务模块，必须大于零
	// 例如: 1-文章, 2-视频, 3-商品等
	Module int32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"` // 校验规则: 模块ID必须大于0，确保指定了有效的业务模块
	// 资源ID，关联的业务资源唯一标识，长度必须大于零
	// 例如: 文章ID、视频ID等
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // 校验规则: 资源ID字符串长度必须大于等于1，确保关联到具体资源
	// 用户信息
	UserId   string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 校验规则: 用户ID字符串长度必须大于等于1，确保指定了评论用户身份
	Username string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`           // 校验规则: 用户名字符串长度必须大于等于1，确保显示名称不为空
	Avatar   string `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`               // 校验规则: 用户头像URL字符串长度必须大于等于1，确保头像信息不为空
	// 评论内容，支持文本和表情，长度必须大于零并且小于两千字符
	Content string `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"` // 校验规则: 评论内容必须介于1-2000字符之间，确保内容不为空且不会过长
	// 评论层级关系
	ParentCommentId int64 `protobuf:"varint,7,opt,name=parent_comment_id,json=parentCommentId,proto3" json:"parent_comment_id,omitempty"` // 校验规则: 父评论ID必须大于等于0，0表示顶级评论
	Level           int32 `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`                                              // 校验规则: 评论层级必须大于等于0，0为顶级评论
	RootCommentId   int64 `protobuf:"varint,9,opt,name=root_comment_id,json=rootCommentId,proto3" json:"root_comment_id,omitempty"`       // 校验规则: 根评论ID必须大于等于0，用于快速查找整个评论链
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCommentRequest) GetModule() int32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *CreateCommentRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateCommentRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateCommentRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetParentCommentId() int64 {
	if x != nil {
		return x.ParentCommentId
	}
	return 0
}

func (x *CreateCommentRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateCommentRequest) GetRootCommentId() int64 {
	if x != nil {
		return x.RootCommentId
	}
	return 0
}

// Comment 评论消息
// 包含评论的基本信息和回复列表
type Comment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 业务模块标识
	Module int32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"` // 校验规则: 模块ID必须大于0，确保指定了有效的业务模块
	// 资源唯一标识
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // 校验规则: 资源ID字符串长度必须大于等于1，确保关联到具体资源
	// 评论唯一标识
	CommentId int64 `protobuf:"varint,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 校验规则: 评论ID必须大于0，确保评论有有效的唯一标识
	// 用户相关字段
	UserId   string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 校验规则: 用户ID字符串长度必须大于等于1，确保指定了评论用户身份
	Username string `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`           // 校验规则: 用户名字符串长度必须大于等于1，确保显示名称不为空
	Avatar   string `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`               // 校验规则: 用户头像URL字符串长度必须大于等于1，确保头像信息不为空
	// 评论内容
	Content string `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"` // 校验规则: 评论内容必须介于1-2000字符之间，确保内容不为空且不会过长
	// 评论层级信息
	Level int32 `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"` // 校验规则: 评论层级必须大于等于0，0为顶级评论
	// 评论点赞数
	LikeCount int64 `protobuf:"varint,11,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"` // 校验规则: 点赞数必须大于等于0，确保数量为非负数
	// 评论回复数
	ReplyCount int64 `protobuf:"varint,12,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"` // 校验规则: 回复数必须大于等于0，确保数量为非负数
	// 回复评论列表
	ReplyComments []*Comment `protobuf:"bytes,9,rep,name=reply_comments,json=replyComments,proto3" json:"reply_comments,omitempty"`
	// 评论时间
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"` // 校验规则: 创建时间必须存在且有效
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_comment_v1_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{5}
}

func (x *Comment) GetModule() int32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *Comment) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Comment) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *Comment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Comment) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Comment) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Comment) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetReplyCount() int64 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Comment) GetReplyComments() []*Comment {
	if x != nil {
		return x.ReplyComments
	}
	return nil
}

func (x *Comment) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

type GetCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 业务模块标识
	Module int32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"` // 校验规则: 模块ID必须大于0，确保指定了有效的业务模块
	// 资源唯一标识
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // 校验规则: 资源ID字符串长度必须大于等于1，确保关联到具体资源
	// 最大层级深度
	MaxDepth int32 `protobuf:"varint,3,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // 校验规则: 最大层级深度必须介于1-10之间，防止查询过深导致性能问题
	// 分页参数
	Page          int32                      `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`                                                                    // 页码，从1开始
	PageSize      int32                      `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`                                            // 每页数量，最大100
	SortType      GetCommentRequest_SortType `protobuf:"varint,6,opt,name=sort_type,json=sortType,proto3,enum=comment.v1.GetCommentRequest_SortType" json:"sort_type,omitempty"` // 根评论排序类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRequest) Reset() {
	*x = GetCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRequest) ProtoMessage() {}

func (x *GetCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{6}
}

func (x *GetCommentRequest) GetModule() int32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *GetCommentRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetCommentRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *GetCommentRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetCommentRequest) GetSortType() GetCommentRequest_SortType {
	if x != nil {
		return x.SortType
	}
	return GetCommentRequest_LIKE_COUNT_DESC
}

type CommentTree struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 评论列表
	Comments      []*Comment `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommentTree) Reset() {
	*x = CommentTree{}
	mi := &file_comment_v1_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommentTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommentTree) ProtoMessage() {}

func (x *CommentTree) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommentTree.ProtoReflect.Descriptor instead.
func (*CommentTree) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{7}
}

func (x *CommentTree) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

// 删除评论
type DeleteCommentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 业务模块标识
	Module int32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"` // 校验规则: 模块ID必须大于0，确保指定了有效的业务模块
	// 资源唯一标识
	ResourceId string `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"` // 校验规则: 资源ID字符串长度必须大于等于1，确保关联到具体资源
	// 评论唯一标识
	CommentId int64 `protobuf:"varint,3,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"` // 校验规则: 评论ID必须大于0，确保指定了要删除的具体评论
	// 用户相关字段
	UserId        string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 校验规则: 用户ID字符串长度必须大于等于1，确保验证删除操作的用户身份
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_comment_v1_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCommentRequest) GetModule() int32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *DeleteCommentRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *DeleteCommentRequest) GetCommentId() int64 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteCommentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 删除结果
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_comment_v1_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_comment_v1_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_comment_v1_comment_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_comment_v1_comment_proto protoreflect.FileDescriptor

const file_comment_v1_comment_proto_rawDesc = "" +
	"\n" +
	"\x18comment/v1/comment.proto\x12\n" +
	"comment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"^\n" +
	"\x12LikeCommentRequest\x12&\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tcommentId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\"P\n" +
	"\fLikeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\tlikeCount\"`\n" +
	"\x14UnlikeCommentRequest\x12&\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tcommentId\x12 \n" +
	"\auser_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\"R\n" +
	"\x0eUnlikeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\n" +
	"like_count\x18\x02 \x01(\x03B\a\xfaB\x04\"\x02(\x00R\tlikeCount\"\xf4\x02\n" +
	"\x14CreateCommentRequest\x12\x1f\n" +
	"\x06module\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06module\x12(\n" +
	"\vresource_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"resourceId\x12 \n" +
	"\auser_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\x12#\n" +
	"\busername\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\busername\x12\x1f\n" +
	"\x06avatar\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06avatar\x12$\n" +
	"\acontent\x18\x06 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xd0\x0fR\acontent\x123\n" +
	"\x11parent_comment_id\x18\a \x01(\x03B\a\xfaB\x04\"\x02(\x00R\x0fparentCommentId\x12\x1d\n" +
	"\x05level\x18\b \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x05level\x12/\n" +
	"\x0froot_comment_id\x18\t \x01(\x03B\a\xfaB\x04\"\x02(\x00R\rrootCommentId\"\xfe\x03\n" +
	"\aComment\x12\x1f\n" +
	"\x06module\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06module\x12(\n" +
	"\vresource_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"resourceId\x12&\n" +
	"\n" +
	"comment_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tcommentId\x12 \n" +
	"\auser_id\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\x12#\n" +
	"\busername\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\busername\x12\x1f\n" +
	"\x06avatar\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06avatar\x12$\n" +
	"\acontent\x18\a \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x01\x18\xd0\x0fR\acontent\x12\x1d\n" +
	"\x05level\x18\b \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x05level\x12&\n" +
	"\n" +
	"like_count\x18\v \x01(\x03B\a\xfaB\x04\"\x02(\x00R\tlikeCount\x12(\n" +
	"\vreply_count\x18\f \x01(\x03B\a\xfaB\x04\"\x02(\x00R\n" +
	"replyCount\x12:\n" +
	"\x0ereply_comments\x18\t \x03(\v2\x13.comment.v1.CommentR\rreplyComments\x12E\n" +
	"\vcreate_time\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\n" +
	"createTime\"\xc7\x02\n" +
	"\x11GetCommentRequest\x12\x1f\n" +
	"\x06module\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06module\x12(\n" +
	"\vresource_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"resourceId\x12&\n" +
	"\tmax_depth\x18\x03 \x01(\x05B\t\xfaB\x06\x1a\x04\x18\n" +
	"(\x01R\bmaxDepth\x12\x1b\n" +
	"\x04page\x18\x04 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04page\x12&\n" +
	"\tpage_size\x18\x05 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\bpageSize\x12C\n" +
	"\tsort_type\x18\x06 \x01(\x0e2&.comment.v1.GetCommentRequest.SortTypeR\bsortType\"5\n" +
	"\bSortType\x12\x13\n" +
	"\x0fLIKE_COUNT_DESC\x10\x00\x12\x14\n" +
	"\x10CREATE_TIME_DESC\x10\x01\">\n" +
	"\vCommentTree\x12/\n" +
	"\bcomments\x18\x01 \x03(\v2\x13.comment.v1.CommentR\bcomments\"\xab\x01\n" +
	"\x14DeleteCommentRequest\x12\x1f\n" +
	"\x06module\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02 \x00R\x06module\x12(\n" +
	"\vresource_id\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"resourceId\x12&\n" +
	"\n" +
	"comment_id\x18\x03 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\tcommentId\x12 \n" +
	"\auser_id\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06userId\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x97\x04\n" +
	"\x0eCommentService\x12b\n" +
	"\rCreateComment\x12 .comment.v1.CreateCommentRequest\x1a\x13.comment.v1.Comment\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/comment\x12]\n" +
	"\n" +
	"GetComment\x12\x1d.comment.v1.GetCommentRequest\x1a\x17.comment.v1.CommentTree\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/api/v1/comment\x12f\n" +
	"\rDeleteComment\x12 .comment.v1.DeleteCommentRequest\x1a\x1a.comment.v1.DeleteResponse\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/api/v1/comment\x12h\n" +
	"\vLikeComment\x12\x1e.comment.v1.LikeCommentRequest\x1a\x18.comment.v1.LikeResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/comment/like\x12p\n" +
	"\rUnlikeComment\x12 .comment.v1.UnlikeCommentRequest\x1a\x1a.comment.v1.UnlikeResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/comment/unlikeBH\n" +
	"\x19dev.kratos.api.comment.v1B\x0eCommentProtoV1P\x01Z\x19comment/api/comment/v1;v1b\x06proto3"

var (
	file_comment_v1_comment_proto_rawDescOnce sync.Once
	file_comment_v1_comment_proto_rawDescData []byte
)

func file_comment_v1_comment_proto_rawDescGZIP() []byte {
	file_comment_v1_comment_proto_rawDescOnce.Do(func() {
		file_comment_v1_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_v1_comment_proto_rawDesc), len(file_comment_v1_comment_proto_rawDesc)))
	})
	return file_comment_v1_comment_proto_rawDescData
}

var file_comment_v1_comment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_comment_v1_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_comment_v1_comment_proto_goTypes = []any{
	(GetCommentRequest_SortType)(0), // 0: comment.v1.GetCommentRequest.SortType
	(*LikeCommentRequest)(nil),      // 1: comment.v1.LikeCommentRequest
	(*LikeResponse)(nil),            // 2: comment.v1.LikeResponse
	(*UnlikeCommentRequest)(nil),    // 3: comment.v1.UnlikeCommentRequest
	(*UnlikeResponse)(nil),          // 4: comment.v1.UnlikeResponse
	(*CreateCommentRequest)(nil),    // 5: comment.v1.CreateCommentRequest
	(*Comment)(nil),                 // 6: comment.v1.Comment
	(*GetCommentRequest)(nil),       // 7: comment.v1.GetCommentRequest
	(*CommentTree)(nil),             // 8: comment.v1.CommentTree
	(*DeleteCommentRequest)(nil),    // 9: comment.v1.DeleteCommentRequest
	(*DeleteResponse)(nil),          // 10: comment.v1.DeleteResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_comment_v1_comment_proto_depIdxs = []int32{
	6,  // 0: comment.v1.Comment.reply_comments:type_name -> comment.v1.Comment
	11, // 1: comment.v1.Comment.create_time:type_name -> google.protobuf.Timestamp
	0,  // 2: comment.v1.GetCommentRequest.sort_type:type_name -> comment.v1.GetCommentRequest.SortType
	6,  // 3: comment.v1.CommentTree.comments:type_name -> comment.v1.Comment
	5,  // 4: comment.v1.CommentService.CreateComment:input_type -> comment.v1.CreateCommentRequest
	7,  // 5: comment.v1.CommentService.GetComment:input_type -> comment.v1.GetCommentRequest
	9,  // 6: comment.v1.CommentService.DeleteComment:input_type -> comment.v1.DeleteCommentRequest
	1,  // 7: comment.v1.CommentService.LikeComment:input_type -> comment.v1.LikeCommentRequest
	3,  // 8: comment.v1.CommentService.UnlikeComment:input_type -> comment.v1.UnlikeCommentRequest
	6,  // 9: comment.v1.CommentService.CreateComment:output_type -> comment.v1.Comment
	8,  // 10: comment.v1.CommentService.GetComment:output_type -> comment.v1.CommentTree
	10, // 11: comment.v1.CommentService.DeleteComment:output_type -> comment.v1.DeleteResponse
	2,  // 12: comment.v1.CommentService.LikeComment:output_type -> comment.v1.LikeResponse
	4,  // 13: comment.v1.CommentService.UnlikeComment:output_type -> comment.v1.UnlikeResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_comment_v1_comment_proto_init() }
func file_comment_v1_comment_proto_init() {
	if File_comment_v1_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_v1_comment_proto_rawDesc), len(file_comment_v1_comment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comment_v1_comment_proto_goTypes,
		DependencyIndexes: file_comment_v1_comment_proto_depIdxs,
		EnumInfos:         file_comment_v1_comment_proto_enumTypes,
		MessageInfos:      file_comment_v1_comment_proto_msgTypes,
	}.Build()
	File_comment_v1_comment_proto = out.File
	file_comment_v1_comment_proto_goTypes = nil
	file_comment_v1_comment_proto_depIdxs = nil
}
