// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: comment/v1/error_reason.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorReason int32

const (
	ErrorReason_GREETER_UNSPECIFIED ErrorReason = 0
	ErrorReason_USER_NOT_FOUND      ErrorReason = 1
)

// Enum value maps for ErrorReason.
var (
	ErrorReason_name = map[int32]string{
		0: "GREETER_UNSPECIFIED",
		1: "USER_NOT_FOUND",
	}
	ErrorReason_value = map[string]int32{
		"GREETER_UNSPECIFIED": 0,
		"USER_NOT_FOUND":      1,
	}
)

func (x ErrorReason) Enum() *ErrorReason {
	p := new(ErrorReason)
	*p = x
	return p
}

func (x ErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_comment_v1_error_reason_proto_enumTypes[0].Descriptor()
}

func (ErrorReason) Type() protoreflect.EnumType {
	return &file_comment_v1_error_reason_proto_enumTypes[0]
}

func (x ErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorReason.Descriptor instead.
func (ErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_comment_v1_error_reason_proto_rawDescGZIP(), []int{0}
}

type SuccessReason int32

const (
	SuccessReason_SUCCESS_UNSPECIFIED SuccessReason = 0
	SuccessReason_SUCCESS             SuccessReason = 200
)

// Enum value maps for SuccessReason.
var (
	SuccessReason_name = map[int32]string{
		0:   "SUCCESS_UNSPECIFIED",
		200: "SUCCESS",
	}
	SuccessReason_value = map[string]int32{
		"SUCCESS_UNSPECIFIED": 0,
		"SUCCESS":             200,
	}
)

func (x SuccessReason) Enum() *SuccessReason {
	p := new(SuccessReason)
	*p = x
	return p
}

func (x SuccessReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SuccessReason) Descriptor() protoreflect.EnumDescriptor {
	return file_comment_v1_error_reason_proto_enumTypes[1].Descriptor()
}

func (SuccessReason) Type() protoreflect.EnumType {
	return &file_comment_v1_error_reason_proto_enumTypes[1]
}

func (x SuccessReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SuccessReason.Descriptor instead.
func (SuccessReason) EnumDescriptor() ([]byte, []int) {
	return file_comment_v1_error_reason_proto_rawDescGZIP(), []int{1}
}

var File_comment_v1_error_reason_proto protoreflect.FileDescriptor

const file_comment_v1_error_reason_proto_rawDesc = "" +
	"\n" +
	"\x1dcomment/v1/error_reason.proto\x12\n" +
	"comment.v1*:\n" +
	"\vErrorReason\x12\x17\n" +
	"\x13GREETER_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSER_NOT_FOUND\x10\x01*6\n" +
	"\rSuccessReason\x12\x17\n" +
	"\x13SUCCESS_UNSPECIFIED\x10\x00\x12\f\n" +
	"\aSUCCESS\x10\xc8\x01B\x1dP\x01Z\x19comment/api/comment/v1;v1b\x06proto3"

var (
	file_comment_v1_error_reason_proto_rawDescOnce sync.Once
	file_comment_v1_error_reason_proto_rawDescData []byte
)

func file_comment_v1_error_reason_proto_rawDescGZIP() []byte {
	file_comment_v1_error_reason_proto_rawDescOnce.Do(func() {
		file_comment_v1_error_reason_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_comment_v1_error_reason_proto_rawDesc), len(file_comment_v1_error_reason_proto_rawDesc)))
	})
	return file_comment_v1_error_reason_proto_rawDescData
}

var file_comment_v1_error_reason_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_comment_v1_error_reason_proto_goTypes = []any{
	(ErrorReason)(0),   // 0: comment.v1.ErrorReason
	(SuccessReason)(0), // 1: comment.v1.SuccessReason
}
var file_comment_v1_error_reason_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_comment_v1_error_reason_proto_init() }
func file_comment_v1_error_reason_proto_init() {
	if File_comment_v1_error_reason_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_comment_v1_error_reason_proto_rawDesc), len(file_comment_v1_error_reason_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_comment_v1_error_reason_proto_goTypes,
		DependencyIndexes: file_comment_v1_error_reason_proto_depIdxs,
		EnumInfos:         file_comment_v1_error_reason_proto_enumTypes,
	}.Build()
	File_comment_v1_error_reason_proto = out.File
	file_comment_v1_error_reason_proto_goTypes = nil
	file_comment_v1_error_reason_proto_depIdxs = nil
}
